// Frontend configuration - you can customize these categories
export const frontendCategories = [
  { id: "popular", name: "Popular", icon: "🔥" },
  { id: "mood", name: "Mood", icon: "😌" },
  { id: "genre", name: "Genre", icon: "🎵" },
  { id: "decade", name: "Decade", icon: "📅" },
  { id: "activity", name: "Activity", icon: "🏃" },
];

// Sub-options for each main category
export const categorySubOptions = {
  popular: [
    { id: "trending", name: "Trending", icon: "📈" },
    { id: "viral", name: "Viral", icon: "🦠" },
    { id: "charts", name: "Charts", icon: "📊" },
    { id: "hits", name: "Hits", icon: "🎯" },
    { id: "top40", name: "Top 40", icon: "🏆" },
  ],
  mood: [
    { id: "chill", name: "Chill", icon: "😌" },
    { id: "energetic", name: "Energetic", icon: "⚡" },
    { id: "romantic", icon: "💕", name: "Romantic" },
    { id: "melancholy", name: "Melancholy", icon: "🌧️" },
    { id: "happy", name: "Happy", icon: "😊" },
    { id: "focused", name: "Focused", icon: "🎯" },
  ],
  genre: [
    { id: "pop", name: "Pop", icon: "🎤" },
    { id: "rock", name: "Rock", icon: "🎸" },
    { id: "hiphop", name: "Hip Hop", icon: "🎧" },
    { id: "electronic", name: "Electronic", icon: "🎛️" },
    { id: "r&b", name: "R&B", icon: "🎹" },
    { id: "country", name: "Country", icon: "🤠" },
    { id: "jazz", name: "Jazz", icon: "🎷" },
    { id: "classical", name: "Classical", icon: "🎻" },
  ],
  decade: [
    { id: "2020s", name: "2020s", icon: "📱" },
    { id: "2010s", name: "2010s", icon: "📱" },
    { id: "2000s", name: "2000s", icon: "💿" },
    { id: "1990s", name: "1990s", icon: "📼" },
    { id: "1980s", name: "1980s", icon: "📻" },
    { id: "1970s", name: "1970s", icon: "🎸" },
    { id: "1960s", name: "1960s", icon: "🌺" },
  ],
  activity: [
    { id: "workout", name: "Workout", icon: "💪" },
    { id: "running", name: "Running", icon: "🏃" },
    { id: "cooking", name: "Cooking", icon: "👨‍🍳" },
    { id: "commute", name: "Commute", icon: "🚗" },
    { id: "gaming", name: "Gaming", icon: "🎮" },
    { id: "travel", name: "Travel", icon: "✈️" },
    { id: "study", name: "Study", icon: "📚" },
    { id: "party", name: "Party", icon: "🎉" },
  ],
};

/**
 * Category -> search terms.
 *
 * 'Curated' browsing is really just a search per term, flattened. Keeping the map
 * here rather than inside the Spotify route is what lets Apple Music reuse it —
 * the terms are plain English, not Spotify-specific.
 */
export const curatedCategoryTerms: Record<string, string[]> = {
    popular: [
      "top hits 2024",
      "viral hits",
      "trending now",
      "popular songs",
      "chart toppers",
    ],
    mood: [
      "chill vibes",
      "workout motivation",
      "party hits",
      "study focus",
      "sleep relaxation",
    ],
    genre: [
      "pop hits",
      "rock classics",
      "hip hop essentials",
      "electronic dance",
      "indie alternative",
      "r&b soul",
      "country favorites",
      "jazz vibes",
      "classical music",
      "reggae beats",
    ],
    // New specific genre categories for frontend
    pop: [
      "pop hits",
      "top 40 hits",
      "mainstream pop",
      "pop classics",
      "chart pop",
    ],
    rock: [
      "rock classics",
      "alternative rock",
      "indie rock",
      "classic rock",
      "hard rock",
    ],
    hiphop: [
      "hip hop essentials",
      "rap hits",
      "trap music",
      "old school hip hop",
      "modern rap",
    ],
    electronic: [
      "electronic dance",
      "edm hits",
      "house music",
      "techno beats",
      "trance music",
    ],
    "r&b": [
      "r&b soul",
      "neo soul",
      "classic soul",
      "contemporary r&b",
      "smooth r&b",
    ],
    country: [
      "country favorites",
      "country hits",
      "folk music",
      "bluegrass",
      "country rock",
    ],
    jazz: [
      "jazz vibes",
      "smooth jazz",
      "blues music",
      "jazz classics",
      "fusion jazz",
    ],
    classical: [
      "classical music",
      "orchestral",
      "piano music",
      "instrumental",
      "film scores",
    ],
    // Popular sub-options
    trending: [
      "trending now",
      "viral hits",
      "trending songs",
      "trending music",
      "trending playlists",
    ],
    viral: [
      "viral hits",
      "viral songs",
      "viral music",
      "viral tiktok",
      "viral trending",
    ],
    charts: [
      "chart toppers",
      "billboard hits",
      "top charts",
      "chart music",
      "chart songs",
    ],
    hits: ["top hits", "hit songs", "popular hits", "hit music", "hits 2024"],
    top40: [
      "top 40 hits",
      "top 40 songs",
      "top 40 music",
      "top 40 radio",
      "top 40 playlist",
    ],
    // Mood sub-options
    chill: [
      "chill vibes",
      "chill music",
      "chill songs",
      "chill playlist",
      "chill beats",
    ],
    energetic: [
      "energetic music",
      "high energy",
      "energetic songs",
      "energy boost",
      "energetic workout",
    ],
    romantic: [
      "romantic songs",
      "romantic music",
      "love songs",
      "romantic playlist",
      "romantic vibes",
    ],
    melancholy: [
      "melancholy music",
      "sad songs",
      "melancholy vibes",
      "emotional music",
      "melancholy playlist",
    ],
    happy: [
      "happy songs",
      "happy music",
      "feel good songs",
      "happy vibes",
      "happy playlist",
    ],
    focused: [
      "focus music",
      "study focus",
      "concentration music",
      "focus playlist",
      "productive music",
    ],
    // Decade sub-options
    "2020s": [
      "2020s hits",
      "2020s music",
      "2020s songs",
      "modern hits",
      "2020s playlist",
    ],
    "2010s": [
      "2010s hits",
      "2010s music",
      "2010s songs",
      "2010s playlist",
      "2010s pop",
    ],
    "2000s": [
      "2000s hits",
      "2000s music",
      "2000s songs",
      "2000s playlist",
      "2000s pop",
    ],
    "1990s": [
      "90s hits",
      "90s music",
      "90s songs",
      "90s playlist",
      "90s classics",
    ],
    "1980s": [
      "80s hits",
      "80s music",
      "80s songs",
      "80s playlist",
      "80s classics",
    ],
    "1970s": [
      "70s hits",
      "70s music",
      "70s songs",
      "70s playlist",
      "70s classics",
    ],
    "1960s": [
      "60s hits",
      "60s music",
      "60s songs",
      "60s playlist",
      "60s classics",
    ],
    // Activity sub-options
    workout: [
      "workout motivation",
      "workout music",
      "gym playlist",
      "fitness music",
      "workout songs",
    ],
    running: [
      "running music",
      "running playlist",
      "jogging music",
      "running songs",
      "cardio music",
    ],
    cooking: [
      "cooking playlist",
      "cooking music",
      "kitchen vibes",
      "cooking songs",
      "chef music",
    ],
    commute: [
      "commute songs",
      "commute music",
      "driving playlist",
      "road trip music",
      "commute vibes",
    ],
    gaming: [
      "gaming soundtrack",
      "gaming music",
      "video game music",
      "gaming playlist",
      "game music",
    ],
    travel: [
      "travel vibes",
      "travel music",
      "travel playlist",
      "vacation music",
      "travel songs",
    ],
    study: [
      "study focus",
      "study music",
      "study playlist",
      "academic music",
      "study songs",
    ],
    party: [
      "party hits",
      "party music",
      "party playlist",
      "party songs",
      "celebration music",
    ],
    decade: [
      "90s hits",
      "2000s pop",
      "2010s hits",
      "classic rock",
      "modern hits",
    ],
    activity: [
      "running music",
      "cooking playlist",
      "commute songs",
      "gaming soundtrack",
      "travel vibes",
    ],
  };
