import { getProvider, type MusicProvider } from "../music";
import { subscribe } from "../subscribe";
import { unsubscribe } from "../unsubscribe";
import { generateTracklist, resolveTracks } from "../generate-playlist";

/**
 * The assistant never mutates the library directly. A mutating tool resolves
 * and validates the request, then returns one of these — a plain-English
 * change the UI renders as a confirm card. Only on the user's "Do it" does the
 * client POST it to `/api/agent/execute`, which runs `executeProposal`.
 */
type PlaylistRef = {
  id: string;
  name: string;
  imageUrl: string | null;
  trackCount: number;
};

export type AgentProposal =
  | {
      action: "subscribe";
      title: string;
      detail: string;
      params: {
        provider: MusicProvider;
        sourcePlaylist: PlaylistRef;
        managedPlaylist?: PlaylistRef;
        newPlaylistName?: string;
        syncFrequency: string;
      };
    }
  | {
      action: "unsubscribe";
      title: string;
      detail: string;
      params: {
        managedPlaylistId: string;
        sourcePlaylistId: string;
        lastSource: boolean;
      };
    }
  | {
      action: "generatePlaylist";
      title: string;
      detail: string;
      params: {
        provider: MusicProvider;
        vibe: string;
        playlistName: string;
        count: number;
      };
    }
  | {
      action: "addArtists";
      title: string;
      detail: string;
      params: {
        provider: MusicProvider;
        managed: PlaylistRef; // external playlist id + metadata for subscribe()
        artists: string[];
        syncFrequency: string;
      };
    };

export interface ExecuteResult {
  ok: boolean;
  message: string;
}

export async function executeProposal(
  userId: string,
  p: AgentProposal,
): Promise<ExecuteResult> {
  switch (p.action) {
    case "subscribe": {
      const r = await subscribe({
        userId,
        provider: p.params.provider,
        sourcePlaylist: p.params.sourcePlaylist,
        managedPlaylist: p.params.managedPlaylist,
        newPlaylistName: p.params.newPlaylistName,
        syncFrequency: p.params.syncFrequency,
      });
      const dest = r.managedPlaylist?.name ?? p.params.newPlaylistName;
      return {
        ok: true,
        message: `Subscribed ${p.params.sourcePlaylist.name} → ${dest}`,
      };
    }

    case "unsubscribe": {
      const r = await unsubscribe({
        userId,
        managedPlaylistId: p.params.managedPlaylistId,
        sourcePlaylistId: p.params.sourcePlaylistId,
      });
      return {
        ok: true,
        message: r.managedPlaylistDeleted
          ? `Stopped managing ${r.playlistName}`
          : `Removed a source from ${r.playlistName}`,
      };
    }

    case "generatePlaylist": {
      const client = await getProvider(p.params.provider).forUser(userId);
      if (!client)
        return { ok: false, message: `${p.params.provider} isn't connected` };

      const suggestions = await generateTracklist(
        p.params.vibe,
        p.params.count,
      );
      const trackIds = await resolveTracks(client, suggestions);
      if (trackIds.length === 0) {
        return {
          ok: false,
          message: "Couldn't find real tracks for that vibe — try rephrasing.",
        };
      }
      const pl = await client.createPlaylist(
        p.params.playlistName,
        `🦊 Generated by PlaylistFox for: ${p.params.vibe}`,
      );
      await client.addTracks(pl.id, trackIds);
      return {
        ok: true,
        message: `Created ${pl.name} with ${trackIds.length} tracks`,
      };
    }

    case "addArtists": {
      const client = await getProvider(p.params.provider).forUser(userId);
      if (!client)
        return { ok: false, message: `${p.params.provider} isn't connected` };

      const done: string[] = [];
      const failed: string[] = [];
      for (const artist of p.params.artists) {
        const hits = await client.searchPlaylists(`This is ${artist}`, 5);
        const officialMix = hits.find(
          (x) =>
            x.owner?.toLowerCase() === "spotify" &&
            x.name.toLowerCase().includes(artist.toLowerCase()),
        );
        const source =
          officialMix ??
          hits[0] ??
          (await client.searchPlaylists(artist, 1))[0];
        if (!source) {
          failed.push(artist);
          continue;
        }
        try {
          await subscribe({
            userId,
            provider: p.params.provider,
            sourcePlaylist: {
              id: source.id,
              name: source.name,
              imageUrl: source.imageUrl,
              trackCount: source.trackCount,
            },
            managedPlaylist: p.params.managed,
            syncFrequency: p.params.syncFrequency,
          });
          done.push(artist);
        } catch {
          failed.push(artist);
        }
      }
      return {
        ok: done.length > 0,
        message:
          `Added ${done.join(", ") || "nothing"}` +
          (failed.length ? ` · couldn't add ${failed.join(", ")}` : ""),
      };
    }
  }
}
