import { tool } from "ai";
import z from "zod";
import { getProvider, MusicProvider } from "../music";
import prisma from "../prisma";
import { subscribe } from "../subscribe";
import { generateTracklist, resolveTracks } from "../generate-playlist";

export function buildTools(userId: string) {
  return {
    searchPlaylists: tool({
      description: "Search a music service for playlists to subscribe to.",
      inputSchema: z.object({
        query: z.string(),
        provider: z.enum(["SPOTIFY", "APPLE_MUSIC"]).default("SPOTIFY"),
      }),
      execute: async ({ query, provider }) => {
        const client = await getProvider(provider as MusicProvider).forUser(
          userId,
        );
        if (!client) return { error: `${provider} isn't connected` };
        return client.searchPlaylists(query, 10);
      },
    }),

    generatePlaylist: tool({
      description:
        "Create a brand-new playlist of songs that match a described vibe or " +
        "mood (NOT sourced from existing playlists). Use this when the user wants " +
        "a playlist built from a description like 'chill rainy-day indie'. " +
        "One-shot — the result is a normal playlist, not auto-synced.",
      inputSchema: z.object({
        vibe: z
          .string()
          .describe("The mood/genre/vibe, e.g. 'late-night synthwave drive'"),
        playlistName: z.string().describe("Name for the new playlist"),
        count: z.number().int().min(5).max(40).default(20),
        provider: z.enum(["SPOTIFY", "APPLE_MUSIC"]).default("SPOTIFY"),
      }),
      execute: async ({ vibe, playlistName, count, provider }) => {
        try {
          const client = await getProvider(provider).forUser(userId);
          if (!client) return { error: `${provider} isn't connected` };

          // 1. Model proposes real songs for the vibe.
          const suggestions = await generateTracklist(vibe, count);
          // 2. Resolve them to real, addable track ids (drops hallucinations).
          const trackIds = await resolveTracks(client, suggestions);
          if (trackIds.length === 0) {
            return {
              error:
                "Couldn't find real tracks for that vibe — try describing it differently.",
            };
          }

          // 3. Create the playlist and fill it.
          const playlist = await client.createPlaylist(
            playlistName,
            `🦊 Generated by PlaylistFox for: ${vibe}`,
          );
          await client.addTracks(playlist.id, trackIds);

          return {
            ok: true,
            provider,
            playlist: playlist.name,
            added: trackIds.length,
            requested: count,
          };
        } catch (error: any) {
          return { error: error?.message ?? "Couldn't generate the playlist" };
        }
      },
    }),

    listManagedPlaylists: tool({
      description: "List the user's managed playlists",
      inputSchema: z.object({}),
      execute: async () =>
        prisma.managedPlaylist.findMany({
          where: { userId, deletedAt: null },
          select: { id: true, name: true, provider: true },
        }),
    }),

    createSubscription: tool({
      description: "Subscribe a source playlist to a managed one.",
      inputSchema: z.object({
        sourcePlaylistId: z.string(),
        newPlaylistName: z.string().optional(),
        managedPlaylistId: z.string().optional(),
        syncFrequency: z.enum(["DAILY", "WEEKLY", "MONTHLY"]).default("WEEKLY"),
        provider: z.enum(["SPOTIFY", "APPLE_MUSIC"]).default("SPOTIFY"),
      }),
      // TODO: re-enable a confirm step once the chat UI can render approvals.
      // needsApproval: true,
      execute: async ({
        sourcePlaylistId,
        newPlaylistName,
        managedPlaylistId,
        syncFrequency,
        provider,
      }) => {
        try {
          const client = await getProvider(provider).forUser(userId);
          if (!client) return { error: `${provider} isn't connected` };

          const source = await client.getPlaylist(sourcePlaylistId);
          if (!source) return { error: "Source playlist not found." };

          // Existing destination? Resolve it from our DB (scoped to the user).
          let managedPlaylist;
          if (managedPlaylistId) {
            const dest = await prisma.managedPlaylist.findFirst({
              where: { id: managedPlaylistId, userId, deletedAt: null },
            });
            if (!dest) return { error: "Destination playlist not found." };
            managedPlaylist = {
              id: dest.externalPlaylistId,
              name: dest.name,
              imageUrl: dest.imageUrl,
              trackCount: dest.trackCount,
            };
          }

          const result = await subscribe({
            userId,
            provider, // ← the fix: was defaulting to SPOTIFY
            sourcePlaylist: {
              id: source.id,
              name: source.name,
              imageUrl: source.imageUrl,
              trackCount: source.trackCount,
            },
            managedPlaylist,
            newPlaylistName,
            syncFrequency,
          });

          // Return a slim summary — never the full nested Prisma object, which
          // bloats the conversation and can break history conversion.
          return {
            ok: true,
            provider,
            playlist: result.managedPlaylist?.name ?? newPlaylistName,
            subscriptionId: result.subscriptionId,
          };
        } catch (error: any) {
          return { error: error?.message ?? "Couldn't create subscription" };
        }
      },
    }),
  };
}
